feat!: add Prisma integration (#22)
catppuccin/discord-bot pull request #24
Opened 2022-07-10 23:35 UTC by DakshG07

Adds a new Interface object to a `db.ts` and support for a Prisma database(through `postgresql`). There may be bugs and/or breaking changes.
(Also fixes a typo in the docs.)
**Might want to thoroughly test and review this PR before merging into main, may contain bugs and/or breaking changes.**
A Postgresql server will need to be running and set via a `DATABASE_URL` environment variable.

2022-07-16 20:44 UTC, nekowinston commented on src/commands/repo_search.ts
> +dotenv.config();
This should not be necessary, since we have it in the `main.ts` already:
https://github.com/catppuccin/discord-bot/blob/dc6c5da37d8bd819edab2b0fc55a2a780f557380/src/main.ts#L13

2022-07-16 20:44 UTC, nekowinston commented on src/commands/repo_search.ts
> +				keys: ["name", "full_name"],
Maybe we should include other fields as well? Such as `topics`, for example. Ideally the OctoKit response could be cleared from `catppuccin` and `colorscheme` topics, so that just application-specific topics remain.

e.g. `gemini` for `amfora`

2022-07-16 20:44 UTC, nekowinston commented on prisma/schema.prisma
> +  cid          String    @default(uuid()) @unique
Still a bit unsure of whether we should not maybe use a Long/BigInt here. Not too much of a concern.

2022-07-16 20:47 UTC, DakshG07 commented on prisma/schema.prisma
> +  cid          String    @default(uuid()) @unique
It's fine with a string.

2022-07-16 20:47 UTC, DakshG07 commented on src/commands/repo_search.ts
> +dotenv.config();
Yeah, there's some ghost code here an there.
Added it here and later added it to the `main.ts`.

2022-07-16 21:06 UTC, nekowinston commented
The CI checks work now, which means that it's only failing because of that legacy `@ts-ignore` annotation now.

Can I also request that in future, we use feature branches to merge against `dev`? The pipeline annotates stuff twice, because both `push` and `pull_request` are the trigger for the `dev` branch.

2022-07-24 19:18 UTC, nekowinston commented on src/events/horniDetect.ts
> +		// A list of horni words, hard-coded into the source code because I'm too lazy to do otherwise
this is fine for now, but we should really either
- keep this as a separate JSON and unmarshal into an Array here
- or keep as a sep. JSON and seed the Database with this data.

2022-07-24 19:18 UTC, nekowinston commented on src/events/horniDetect.ts
> +				"https://c.tenor.com/TKbDxDPCkegAAAAC/horny-jail-go-to-horny-jail.gif"
same thing goes for this one, maybe load it from the ENV or the bot config.

2022-07-25 20:06 UTC, DakshG07 commented on src/events/horniDetect.ts
> +		// A list of horni words, hard-coded into the source code because I'm too lazy to do otherwise
I say seed the DB. It’ll work a lot nicer. I’ll implement this once I get time.

2022-07-25 20:07 UTC, DakshG07 commented on src/events/horniDetect.ts
> +				"https://c.tenor.com/TKbDxDPCkegAAAAC/horny-jail-go-to-horny-jail.gif"
The `bot_config.js` was a bad idea, all bot secrets are now stored in `.env`.
Also, not entirely sure what you’d actually *load*.

2022-07-25 20:09 UTC, DakshG07 commented
The `@ts-ignore`s have been removed, along with any leaked template code.
I’ve also cleaned up some of the files.
Certain features will most likely have a more robust implementation in the future. I just want to make sure we can get the base of it down first.

2022-07-25 20:09 UTC, nekowinston commented on src/events/horniDetect.ts
> +				"https://c.tenor.com/TKbDxDPCkegAAAAC/horny-jail-go-to-horny-jail.gif"
The response GIF should be changeable without modifying the source code.
A file like `bot_config.ts` itself is not the issue, as long as we correctly unmarshal the config there.

2022-07-25 21:42 UTC, DakshG07 commented on src/commands/repo_search.ts
> +dotenv.config();
Fixed.

2022-07-25 21:44 UTC, DakshG07 commented
> The CI checks work now, which means that it's only failing because of that legacy `@ts-ignore` annotation now.
> 
> Can I also request that in future, we use feature branches to merge against `dev`? The pipeline annotates stuff twice, because both `push` and `pull_request` are the trigger for the `dev` branch.

That seems to have mostly been some leaked in code from @BlueFalconHD ‘s work on the pin system. Every other issue has been resolved(as I needed to fix them in order to push my code, due to pre-commit hooks).

2022-08-04 00:50 UTC, DakshG07 commented on src/events/horniDetect.ts
> +				"https://c.tenor.com/TKbDxDPCkegAAAAC/horny-jail-go-to-horny-jail.gif"
Code now reads from the `.env` :)

2022-08-13 16:46 UTC, nekowinston requested changes

2022-08-13 16:46 UTC, nekowinston commented on .gitignore
> +commit.bat
Sorry to maybe be pedantic, but you also added `commit.bat` in the same commit, was that intentional?

2022-08-13 16:46 UTC, nekowinston commented on src/commands/repo_search.ts
> +				keys: ["name", "full_name"],
If we could get `topics` included as well, I'd say this is finally ready for a merge, so that we have a common code base again, at least.

2022-08-23 14:44 UTC, DakshG07 commented on .gitignore
> +commit.bat
nope I’m an idiot

2022-08-23 14:45 UTC, DakshG07 commented
pls merge

2022-08-23 14:46 UTC, nekowinston approved these changes

2022-08-23 14:47 UTC, merged